init python:
    DefineImages("images/test")
    DefineImages("cgs")
    DefineImages("bgs")
    DefineImages("sprites", composite=True, overrideLayerOrder=['base', 'hood', 'cape', 'flame', 'lantern', 'mouth', 'eyes', 'brow', 'blush', 'sweat',],
        zooms={'her': 1.2, 'ald':1.2}, sides=['her', 'ald'])

    ##### HERLEVA #####
    # h_ = with hood
    MapEmote('her normal', 'her base md_default ed_default brow_default')
    MapEmote('her sigh', 'her base mdo_default ec_default brow_default')
    MapEmote('her neutral', 'her base md_frown ed_lower brow_default')
    MapEmote('her curious', 'her base md_tch ed_side brow_default')
    MapEmote('her hopelesssmile', 'her base md_default ed_lowerside brow_default')
    MapEmote('her tch', 'her base md_tch ed_default brow_default')
    MapEmote('her speaking', 'her base mdo_default ed_default brow_default')
    MapEmote('her grin', 'her base md_grin ed_lower brow_default')
    MapEmote('her hopelessresponse', 'her base mdo_default ed_lowerside brow_default')
    MapEmote('her smile_ec', 'her base md_grin ec_default brow_default')
    MapEmote('her speaking_angry', 'her base mdo_default ed_default brow_furious')
    MapEmote('her smile_confident', 'her base md_grin ed_default brow_angry')
    MapEmote('her tch_angry', 'her base md_tch ed_lowerside brow_furious')
    MapEmote('her pout', 'her base mdo_default ed_lowerside brow_angry')
    MapEmote('her shouting_neutral', 'her base mdo_wide ed_lower brow_default')
    MapEmote('her surprised', 'her base mdo_default ed_surprised brow_default')
    MapEmote('her NEWEMOTE', 'her base md_tch ed_side brow_default')
    MapEmote('her shouting_ec', 'her base mdo_wide ec_default brow_angry')
    MapEmote('her smile_angry_ec', 'her base md_default ec_default brow_furious')
    MapEmote('her smile_angry_eo', 'her base md_grin ed_lower brow_furious')


    MapEmote('her normal_h', 'her base hood md_default ed_default brow_default')
    MapEmote('her sigh_h', 'her base hood mdo_default ec_default brow_default')
    MapEmote('her neutral_h', 'her base hood md_frown ed_lower brow_default')
    MapEmote('her curious_h', 'her base hood md_tch ed_side brow_default')
    MapEmote('her hopelesssmile_h', 'her base hood md_default ed_lowerside brow_default')
    MapEmote('her tch_h', 'her base hood md_tch ed_default brow_default')
    MapEmote('her speaking_h', 'her base hood mdo_default ed_default brow_default')
    MapEmote('her grin_h', 'her base hood md_grin ed_lower brow_default')
    MapEmote('her hopelessresponse_h', 'her base hood mdo_default ed_lowerside brow_default')
    MapEmote('her smile_ec_h', 'her base hood md_grin ec_default brow_default')
    MapEmote('her speaking_angry_h', 'her base hood mdo_default ed_default brow_furious')
    MapEmote('her smile_confident_h', 'her base hood md_grin ed_default brow_angry')
    MapEmote('her tch_angry_h', 'her base hood md_tch ed_lowerside brow_furious')
    MapEmote('her pout_h', 'her base hood mdo_default ed_lowerside brow_angry')
    MapEmote('her shouting_neutral_h', 'her base hood mdo_wide ed_lower brow_default')
    MapEmote('her surprised_h', 'her base hood mdo_default ed_surprised brow_default')
    MapEmote('her NEWEMOTE_h', 'her base hood md_tch ed_side brow_default')
    MapEmote('her shouting_ec_h', 'her base hood mdo_wide ec_default brow_angry')
    MapEmote('her smile_angry_ec_h', 'her base hood md_default ec_default brow_furious')
    MapEmote('her smile_angry_eo_h', 'her base hood md_grin ed_lower brow_furious')
    MapEmote('her sigh_angry_ec_h', 'her base hood mdo_default ec_default brow_furious')

    MapEmote('her grimace_h', 'her base hood md_frown ec_default brow_furious')
    MapEmote('her sad_h', 'her base hood md_frown ed_lowerside brow_confused')
    MapEmote('her disgusted_h', 'her base hood mdo_default ed_surprised brow_confused')

    ##### ALDEBRAND #####
    # c_ = with cape
    MapEmote('ald normal', 'ald base flame_default lantern_default md_default ed_default brow_default')
    MapEmote('ald c_normal', 'ald base cape flame_default lantern_default md_default ed_default brow_default')
    MapEmote('ald c_normal fn', 'ald base cape flame_none lantern_default md_default ed_default brow_default')
    MapEmote('ald surprised fn', 'ald base flame_none lantern_default mdo_ah ed_default brow_raised')
    MapEmote('ald sly fn', 'ald base flame_none lantern_default mdo_default ed_lowered brow_raised')
    MapEmote('ald sly_wink fn', 'ald base flame_none lantern_default mdo_default ed_wink brow_stern')

    MapEmote('ald pout fd', 'ald base flame_default lantern_default md_pout ed_loweredsideeye brow_soften')
    MapEmote('ald sad fd', 'ald base flame_default lantern_default md_frown ed_loweredsideeye brow_worry')
    MapEmote('ald wink fd', 'ald base flame_default lantern_default mdo_default ed_wink brow_default')
    MapEmote('ald happy_ec fn', 'ald base flame_none lantern_default mdo_default ec_default brow_raised')
    MapEmote('ald sly_cape fd', 'ald base cape flame_blue lantern_default mdo_default ed_lowered brow_raised')
    MapEmote('ald sly_wink_cape fd', 'ald base cape flame_blue lantern_default mdo_default ed_wink brow_stern')
    MapEmote('ald smile_ec fd', 'ald base cape flame_blue lantern_default mdo_default ec_default brow_default')
    MapEmote('ald smile_sideeye fd', 'ald base cape flame_blue lantern_default mdo_default ed_sideeye brow_raised')
    MapEmote('ald smile_neutral fd', 'ald base cape flame_blue lantern_default mdo_default ed_default brow_raised')
    MapEmote('ald serious_cape fd', 'ald base cape flame_blue lantern_default md_frown ed_lowered brow_stern')
    MapEmote('ald neutral_cape fd', 'ald base cape flame_blue lantern_default md_pout ed_lowered brow_stern')
    MapEmote('ald curious_cape fd', 'ald base cape flame_default lantern_default md_ugh ed_default brow_confused')
    MapEmote('ald concerned_cape fd', 'ald base cape flame_default lantern_default md_pout ed_default brow_soften')
    MapEmote('ald annoyed_speaking fd', 'ald base cape flame_default lantern_default md_ugh ed_loweredsideeye brow_soften')
    MapEmote('ald disgusted_cape fd', 'ald base cape flame_default lantern_default md_ugh ec_default brow_furious')
    MapEmote('ald surprised_cape fd', 'ald base cape flame_default lantern_default mdo_ah ed_sideeye brow_raised')

    MapEmote('ald pout fn', 'ald base flame_none lantern_default md_pout ed_loweredsideeye brow_soften')
    MapEmote('ald sad fn', 'ald base flame_none lantern_default md_frown ed_loweredsideeye brow_worry')
    MapEmote('ald wink fn', 'ald base flame_none lantern_default mdo_default ed_wink brow_default')
    MapEmote('ald pout_cape fn', 'ald base cape flame_none lantern_default md_pout ed_loweredsideeye brow_soften')
    MapEmote('ald sly_cape fn', 'ald base cape flame_none lantern_default mdo_default ed_lowered brow_raised')
    MapEmote('ald sly_wink_cape fn', 'ald base cape flame_none lantern_default mdo_default ed_wink brow_stern')
    MapEmote('ald smile_ec fn', 'ald base cape flame_none lantern_default mdo_default ec_default brow_default')
    MapEmote('ald smile_sideeye fn', 'ald base cape flame_none lantern_default mdo_default ed_sideeye brow_raised')
    MapEmote('ald smile_neutral fn', 'ald base cape flame_none lantern_default mdo_default ed_default brow_raised')
    MapEmote('ald serious_cape fn', 'ald base cape flame_none lantern_default md_frown ed_lowered brow_stern')
    MapEmote('ald neutral_cape fn', 'ald base cape flame_none lantern_default md_pout ed_lowered brow_stern')
    MapEmote('ald curious_cape fn', 'ald base cape flame_none lantern_default md_ugh ed_default brow_confused')
    MapEmote('ald concerned_cape fn', 'ald base cape flame_none lantern_default md_pout ed_default brow_raised')
    MapEmote('ald annoyed_speaking fn', 'ald base cape flame_none lantern_default md_ugh ed_loweredsideeye brow_soften')
    MapEmote('ald disgusted_cape fn', 'ald base cape flame_none lantern_default md_ugh ec_default brow_furious')
    MapEmote('ald surprised_cape fn', 'ald base cape flame_none lantern_default mdo_ah ed_sideeye brow_raised')
    MapEmote('ald sigh_cape fn', 'ald base cape flame_none lantern_default mdo_ah ec_default brow_default')
    MapEmote('ald frown_cape fn', 'ald base cape flame_none lantern_default md_frown ed_loweredsideeye brow_angry')
    MapEmote('ald suspicious_cape fn', 'ald base cape flame_none lantern_default md_pout ed_loweredsideeye brow_confused')
    MapEmote('ald speaking_cape fn', 'ald base cape flame_none lantern_default mdo_ah ed_default brow_default')
    MapEmote('ald happy_ec_cape fn', 'ald base cape flame_none lantern_default mdo_default ec_default brow_raised')
    MapEmote('ald casting_cape fn', 'ald base cape flame_blue lantern_default md_ugh ed_default brow_soften sweat')
    MapEmote('ald shouting_cape fn', 'ald base cape flame_default lantern_none mdo_ah ed_lowered brow_angry')
    MapEmote('ald speaking_serious_cape fn', 'ald base cape flame_default lantern_default md_ugh ed_lowered brow_angry')
    MapEmote('ald injured_cape fn', 'ald base cape flame_none lantern_default md_ugh ed_wink brow_confused')

    MapEmote('ald embarassed_cape fn', 'ald base cape flame_none lantern_default md_frown ed_sideeye brow_raised blush')
    MapEmote('ald sad_cape fn', 'ald base cape flame_none lantern_default md_frown ed_lowered brow_worry')
    MapEmote('ald sad_ec fn', 'ald base flame_none lantern_none md_ugh ec_default brow_angry')

    MapEmote('ald neutral_fn', 'ald base flame_none lantern_default md_pout ed_lowered brow_stern')
    MapEmote('ald injured_fn', 'ald base flame_none lantern_default md_ugh ed_wink brow_confused')
    MapEmote('ald surprised_fn', 'ald base flame_none lantern_default mdo_ah ed_sideeye brow_raised')
    MapEmote('ald disgusted_fn', 'ald base flame_none lantern_default md_ugh ec_default brow_furious')
    MapEmote('ald smile_ec_fn', 'ald base flame_none lantern_default mdo_default ec_default brow_default')
    MapEmote('ald speaking_fn', 'ald base flame_none lantern_default mdo_ah ed_default brow_default')
    MapEmote('ald annoyed_speaking_fn', 'ald base flame_none lantern_default md_ugh ed_loweredsideeye brow_soften')
    MapEmote('ald speaking_serious_fn', 'ald base flame_default lantern_default md_ugh ed_lowered brow_angry')
    MapEmote('ald shouting_fn', 'ald base flame_default lantern_none mdo_ah ed_lowered brow_angry')
    MapEmote('ald happy_ec_fn', 'ald base flame_none lantern_default mdo_default ec_default brow_raised')
    MapEmote('ald sigh_fn', 'ald base flame_none lantern_default mdo_ah ec_default brow_default')
    MapEmote('ald sly_fn', 'ald base flame_none lantern_default mdo_default ed_lowered brow_raised')
    MapEmote('ald sly_wink_fn', 'ald base flame_none lantern_default mdo_default ed_wink brow_stern')
    MapEmote('ald frown_fn', 'ald base flame_none lantern_default md_frown ed_loweredsideeye brow_angry')
    MapEmote('ald pout_fn', 'ald base flame_none lantern_default md_pout ed_loweredsideeye brow_soften')
    MapEmote('ald sad_fn', 'ald base flame_none lantern_default md_frown ed_loweredsideeye brow_worry')
    MapEmote('ald sad_ec_fn', 'ald base flame_none lantern_none md_ugh ec_default brow_angry')
